name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  # Jupyter
  - jupyterlab=2.1.3
  - nodejs
  - widgetsnbextension
  # Python kernel
  - altair=4
  - altair_saver
  - beautifulsoup4=4.9
  - geopandas
  - h5py
  - ipywidgets
  - matplotlib-base
  - numba
  - numpy
  - pandas
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - rise
  - scikit-image
  - scikit-learn=0.23
  - scipy
  - seaborn
  - statsmodels
  - sympy
  - vega_datasets
  - xlrd